# Generated by Django 5.0.6 on 2024-09-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_field', models.CharField(max_length=255)),
                ('company_size', models.CharField(choices=[('small', '(1-50 employees)'), ('medium', '(51-200 employees)'), ('large', '(201-500 employees)'), ('enterprise', '(500+ employees)')], max_length=255)),
                ('company_website', models.URLField(max_length=255)),
                ('linkedin', models.URLField(max_length=255)),
                ('why', models.TextField()),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_mail', models.EmailField(max_length=255)),
                ('contact_phone', models.CharField(max_length=255)),
                ('contact_position', models.CharField(max_length=255)),
            ],
        ),
    ]
