# Generated by Django 5.0.6 on 2024-09-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_remove_partner_why'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='why',
            field=models.TextField(default=''),
        ),
    ]
