# Generated by Django 5.0.6 on 2024-09-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_partner_why'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='company_size',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='linkedin',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='why',
            field=models.CharField(max_length=255),
        ),
    ]
