# Generated by Django 5.0.6 on 2024-09-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_alter_partner_company_size_alter_partner_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='linkedin',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='why',
            field=models.TextField(default=''),
        ),
    ]
