# Generated by Django 5.0.6 on 2024-09-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_alter_partner_linkedin_alter_partner_why'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='why',
            field=models.CharField(max_length=255),
        ),
    ]
