# Generated by Django 5.0.6 on 2024-09-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_alter_partner_why'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='linkedin',
            field=models.CharField(max_length=255),
        ),
    ]
