# Generated by Django 5.0.6 on 2024-09-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_alter_partner_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='linkedin',
            field=models.URLField(max_length=255),
        ),
    ]
