# Generated by Django 5.0.6 on 2024-09-18 15:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_alter_partner_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
