# Generated by Django 5.0.6 on 2024-09-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_partner_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='country_code2',
            field=models.CharField(default=20, max_length=3),
        ),
    ]
