# Generated by Django 5.0.6 on 2024-09-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_partner_country_code2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='company_website',
            field=models.CharField(max_length=255),
        ),
    ]
