# Generated by Django 5.1 on 2024-09-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('PersonalEmail', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('telegram_username', models.CharField(max_length=50, unique=True)),
                ('nationality', models.CharField(choices=[('Algeria', 'Algeria'), ('Bahrain', 'Bahrain'), ('Benin', 'Benin')], max_length=50)),
                ('AiesecEmail', models.EmailField(max_length=254, unique=True)),
                ('Position', models.CharField(max_length=50)),
            ],
        ),
    ]
