# Generated by Django 5.0.6 on 2024-09-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='AiesecEmail',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='PersonalEmail',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='Position',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='aiesec_mail',
            field=models.EmailField(default='default@aiesec.net', max_length=254),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='natonality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='personal_mail',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
