# Generated by Django 5.0.6 on 2024-09-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0002_remove_userregistration_aiesecemail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='natonality',
            new_name='nationality',
        ),
    ]
