# Generated by Django 5.0.6 on 2024-09-08 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0003_rename_natonality_userregistration_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
