# Generated by Django 5.0.6 on 2024-09-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0004_userregistration_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='allergies',
            field=models.CharField(blank=True, choices=[("I don't have any allergies or food preferences", "I don't have any allergies or food preferences"), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Lactose-free', 'Lactose-free'), ('Gluten-free', 'Gluten-free'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='expectations',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='experiences',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='motivation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='unique_events',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
