# Generated by Django 5.0.6 on 2024-09-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0005_userregistration_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
