# Generated by Django 5.0.6 on 2024-09-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0006_userregistration_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
