# Generated by Django 5.0.6 on 2024-09-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0007_userregistration_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='entity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
