# Generated by Django 5.0.6 on 2024-09-17 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0008_userregistration_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
