# Generated by Django 5.0.6 on 2024-09-18 00:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0009_userregistration_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
