# Generated by Django 5.0.6 on 2024-09-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0010_alter_userregistration_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='country_code',
            field=models.CharField(default=20, max_length=3),
        ),
    ]
