# Generated by Django 5.0.6 on 2024-09-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0011_userregistration_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
    ]
