# Generated by Django 5.0.6 on 2024-09-21 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0012_userregistration_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='personal_mail',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='arrival',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='assistance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='country_code1',
            field=models.CharField(default=20, max_length=3),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='emergency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='expectations_cc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='expectations_faci',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='expiry',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='invitation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='issue',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='lc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='leaving',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='nickname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='passport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/passports'),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='visa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='visa_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/personal'),
        ),
    ]
